app = 'v08-wildwood-dental'
primary_region = 'ord'

[build]

[env]
  SPARKABLE_CMS = 'true'
  HOST = '0.0.0.0'
  __VITE_ADDITIONAL_SERVER_ALLOWED_HOSTS = 'v08-wildwood-dental.fly.dev'
  SPARKABLE_DATA_DIR = '/app/site-data/.sparkable'
  GITHUB_ORG = 'Carenetic-Digital'
  GITHUB_REPO = 'Wildwood-Dental-CDS'

[http_service]
  internal_port = 4321
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 1

[[http_service.checks]]
  interval = '10s'
  timeout = '5s'
  grace_period = '30s'
  method = 'GET'
  path = '/_sparkable/login'

[mounts]
  source = 'site_data'
  destination = '/app/site-data'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '1gb'
